config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  get "/items/deleted", to: "items#deleted"

  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/deletion.rb
class Deletion < ApplicationRecord
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :deletions, dependent: :destroy

  validates_presence_of :name, presence: true, message: "is missing"
  validates_presence_of :price, presence: true, message: "is missing"

  attr_accessor :comment
  attr_accessor :deletion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deletions_controller.rb
class DeletionsController < ApplicationController
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.where(:deletion_id => nil).all
    @deleted_successfully = params[:deleted]
  end

  def deleted
    @items = Item.where.not(:deletion_id => nil).all
    @items.each do |item|
      item.deletion = Deletion.find(item.deletion_id)
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
    @deletion = Deletion.new
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.deletion_id = item.deletions.create(destroy_item_params).id
    item.save

    redirect_to root_url('deleted' => item.name)
  end

  private
    def item_params
      if params[:item][:deletion_id] == "nil"
        params[:item][:deletion_id] = nil
      end
      params.require(:item).permit(:name, :price, :deletion_id)
    end
    def destroy_item_params
      params.require(:item).permit(:comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deletions_helper.rb
module DeletionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/deletions/_deletion.html.erb
<tr>
  <td><%= deletion.created_at %></td>
  <td><%= deletion.comment %></td>
</tr>


app/views/deletions/_form.html.erb
<%= form_with model: [ @item, @item.deletions.build ] do |form| %>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_field :comment %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/items/_form.html.erb
<style>
  div {
      display: inline;
  }
</style>

<%= form_with model: item do |form| %>
  <%= form.text_field :name, class: "item_name", placeholder: "Name" %>
  <% item.errors.full_messages_for(:name).each do |message| %>
    <script>
      alert("<%= message %>")
    </script>
  <% end %>

  <%= form.number_field :price, class: "item_price", placeholder: "Price" %>
  <% item.errors.full_messages_for(:price).each do |message| %>
    <script>
        alert("<%= message %>")
    </script>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/items/deleted.html.erb
<h4>Deleted Inventory Items</h4>

<% if @items.any? %>
  <p>=------------ Name ------------=------------- Price -------------=---- Deletion Comment ----=</p>
<% end %>

<% @items.each do |item| %>
  <div>
    <div class="item">
      <input class="item_name" disabled value="<%= item.name %>">
      <input class="item_price" disabled value="<%= item.price %>">
      <input class="item_comment" disabled value="<%= item.deletion.comment %>"
    </div>
    <%= form_with model: item do |form| %>
      <%= hidden_field_tag "item[deletion_id]", "nil"  %>
      <%= form.submit "Undo Delete", class: "item_delete item_undelete" %>
    <% end %>
    <%= button_to "View Deletion History", item_path(item), :method => "get", :class => "item_view_history"  %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h4>Edit <span style="color: red"><%= @item.name %></span></h4>

<%= render "form", item: @item %>

<h4>Delete</h4>
<%= form_for(@item, :html => { :method => :delete, :remote => true }) do |form| %>
  <%= form.text_field :comment, class: "item_name", placeholder: "Comment" %>
  <%= form.submit "Delete", :class => "item_delete" %>
<% end %>

app/views/items/index.html.erb
<h4>Inventory Items</h4>

<div class="nav">
    <%= button_to "New Item", new_item_path, :method => "get", :class => "items_new" %>
    <%= button_to "Deleted Items", "/items/deleted", :method => "get", :class => "items_deleted" %>
</div>

<% if @items.any? %>
    <p>=------------ Name ------------=------------ Price ------------=</p>
<% end %>

<% @items.each do |item| %>
    <div class="item">
      <input class="item_name" disabled value="<%= item.name %>">
      <input class="item_price" disabled value="<%= item.price %>">
      <%= button_to "Modify", edit_item_path(item), :class => "item_edit", :method => "get" %>
      <%= button_to "View Deletion History", item_path(item), :method => "get", :class => "item_view_history"  %>
    </div>
<% end %>

<% if @deleted_successfully %>
    <script>
      alert("<%= @deleted_successfully %> has been deleted successfully.")
    </script>
<% end %>

app/views/items/new.html.erb
<h4>New Inventory Item</h4>

<%= render "form", item: @item %>

app/views/items/show.html.erb
<h4>Deletion History for <span style="color: red;"><%= @item.name %></span></h4>

<table class="table_history">
  <tr>
    <td>Date</td>
    <td>Deletion</td>
  </tr>
  <%= render @item.deletions %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventorify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/items.html.erb
<html>
<head>
  <title>Inventorify ~ Home</title>
  <link rel="stylesheet" href="/css/style.css">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
<a href="/">
  <h1 class="title">~ Inventorify ~</h1>
</a>
<h5 class="title">a simple inventory management system</h5>

<%= yield %>

<footer>
  made for <a href="https://shopify.com" target="_blank" class="shopify">shopify</a> by <a class="bassel" target="_blank" href="https://www.linkedin.com/in/basselashi/">Bassel Ashi</a>
</footer>
</body>
</html>